### ISSUE TITLE
Access to the cloud through Web navigator

### ISSUE THREAD

**Issue by mj0123456789** [initml/clipdrop#1]
Hello,
I'd love to be able to access my recorded images in the cloud through a Web navigator.
Do you think about proposing that?
That would help since I mostly work on Linux...
And don't mind importing images into my image editor.
Regards,
Marc
PS : I suggest that you think about developing a Linux version.

**Comment by cyrildiagne** [comment]
Hello Marc,

Thanks a lot for the suggestion!

A Linux version of the Desktop application may be implemented at some point but it's not yet at the top of our roadmap.

But we definitely want to provide access to the Cloud Gallery on the web. You've got a good point that it could be an intermediary solution for users on Linux (Ubuntu, ChromeOS..etc)!
It's a feature we plan to implement soon even though we can't give an ETA just yet.

All the best!
