### ISSUE TITLE
Not available for Linux

### ISSUE THREAD

**Issue by p3k** [initml/clipdrop#3]
Will there be a version of the ClipDrop application for Linux desktops? Is there an estimated timeline?

Oh, and will there be open source code here, or is this repository rather FOSS-washing?

**Comment by cyrildiagne** [comment]
"FOSS-washing"... Nice to meet you too 😒

The prototype is open source & MIT license: https://github.com/cyrildiagne/ar-cutpaste

**Comment by p3k** [comment]
please forgive for hitting a nerve but coming from the [product page](https://clipdrop.co/) there is not much to see what this repository is about. just adding the link to the prototype and a small sentence in the readme might improve the experience.

actually, the issue is about linux support – and i am aware i might have spoiled an answer with my snarky question –, but i am still interested if i will be able to use clipdrop on the platform i use.
